// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBbOSyg1teuMlUsJUmYLY7DQKZRhNUt3OA',
    appId: '1:625472218497:web:fded86b76c5634ba4bf480',
    messagingSenderId: '625472218497',
    projectId: 'show-ad4de',
    authDomain: 'show-ad4de.firebaseapp.com',
    storageBucket: 'show-ad4de.appspot.com',
    measurementId: 'G-MFVMPDT9K8',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyASB2ypylqQIf4Lnj3JessVbSgZDd91XgY',
    appId: '1:625472218497:android:18cda45f9e769fb24bf480',
    messagingSenderId: '625472218497',
    projectId: 'show-ad4de',
    storageBucket: 'show-ad4de.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBuxVi36TGTjCF4WpXwtjVlNpTXdxT38yc',
    appId: '1:625472218497:ios:255e76be89da8cd34bf480',
    messagingSenderId: '625472218497',
    projectId: 'show-ad4de',
    storageBucket: 'show-ad4de.appspot.com',
    iosBundleId: 'com.example.tiktokClone2023',
  );
}
